name: Build

on:
  schedule:
    - cron: '0 0 * * 0' # At 00:00 on Friday

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: |
            cd build
            docker build -t aosp .
            docker stop aosp && docker rm aosp || true
            docker run --name aosp --rm -it --detach --privileged --env GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }} aosp /bin/bash
            docker exec aosp /bin/sh -c "git clone https://github.com/ponces/treble_aosp"

  build:
    needs: setup
    runs-on: self-hosted
    steps:
      - name: Build ROM
        run: docker exec aosp /bin/sh -c "bash treble_aosp/build.sh"

  upload:
    needs: build
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Upload to GitHub
        run: docker exec aosp /bin/sh -c "bash treble_aosp/upload.sh"

  cleanup:
    needs: upload
    runs-on: self-hosted
    steps:
      - name: Cleanup
        run: docker exec aosp /bin/sh -c "docker stop aosp && docker rm aosp"
        
